apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-sentry-exporter.fullname" . }}
  labels:
    {{- include "prometheus-sentry-exporter.labels" . | nindent 4 }}
data:
  SENTRY_HOST: {{ .Values.sentry.host }}
