apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-sentry-exporter.fullname" . }}
  labels:
    {{- include "prometheus-sentry-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prometheus-sentry-exporter.selectorLabels" . | nindent 4 }}
